name: Cygwin Build

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Cygwin
      run: |
        choco install cygwin
        choco install cyg-get
        cyg-get gcc-g++ gcc-core cygwin32-gcc-g++ cygwin32-gcc-core make gcc-fortran gcc-objc gcc-objc++ libkrb5-devel libkrb5_3 libreadline-devel libssl-devel libwrap-devel tcp_wrappers 

    - name: Configure Environment
      run: |
        echo "C:\tools\cygwin\bin" >> $GITHUB_PATH

    - name: Download and Extract the archive
      run: |
        curl -O http://www.dest-unreach.org/socat/download/socat-1.8.0.0.tar.gz
        tar -xvzf socat-1.8.0.0.tar.gz

    - name: Execute Build Script in Cygwin
      run: |
        C:\tools\cygwin\bin\bash -lc "cd /cygdrive/d/a/socat_windows/socat_windows/socat-1.8.0.0 && ./configure && make && make install"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: extracted-socat-1.8.0.0
        path: socat-1.8.0.0/
