name: Cygwin Build

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Cygwin
      run: |
        choco install cygwin
        choco install cyg-get
        cyg-get gcc-g++ gcc-core cygwin32-gcc-g++ cygwin32-gcc-core make gcc-fortran gcc-objc gcc-objc++ libkrb5-devel libkrb5_3 libreadline-devel libssl-devel libwrap-devel tcp_wrappers 

    - name: Configure Environment
      run: |
        echo "C:\tools\cygwin\bin" >> $GITHUB_PATH

    - name: Download and Extract the archive
      run: |
        curl -O http://www.dest-unreach.org/socat/download/socat-1.8.0.0.tar.gz
        tar -xvzf socat-1.8.0.0.tar.gz

    - name: Execute Build Script in Cygwin
      run: |
        C:\tools\cygwin\bin\bash -lc "cd /cygdrive/d/a/socat_windows/socat_windows/socat-1.8.0.0 && ./configure && make && make install"
        
    - name: Copy Cygwin DLLs
      run: |
        Copy-Item "C:\tools\cygwin\bin\cygcrypto-3.dll" -Destination "D:\a\socat_windows\socat_windows\socat-1.8.0.0"
        Copy-Item "C:\tools\cygwin\bin\cygwin1.dll" -Destination "D:\a\socat_windows\socat_windows\socat-1.8.0.0"
        Copy-Item "C:\tools\cygwin\bin\cygssl-3.dll" -Destination "D:\a\socat_windows\socat_windows\socat-1.8.0.0"
        Copy-Item "C:\tools\cygwin\bin\cygreadline7.dll" -Destination "D:\a\socat_windows\socat_windows\socat-1.8.0.0"
        Copy-Item "C:\tools\cygwin\bin\cygwrap-0.dll" -Destination "D:\a\socat_windows\socat_windows\socat-1.8.0.0"
        Copy-Item "C:\tools\cygwin\bin\cygncursesw-10.dll" -Destination "D:\a\socat_windows\socat_windows\socat-1.8.0.0"
        Copy-Item "C:\tools\cygwin\bin\cygz.dll" -Destination "D:\a\socat_windows\socat_windows\socat-1.8.0.0"
      shell: pwsh

    - name: Upload Artifacts
      if: ${{  success() }}
      uses: actions/upload-artifact@v2
      with:
        name: socat-1.8.0.0
        path: socat-1.8.0.0/

    - name: Archive production artifacts
      if: ${{  success() }}
      run: 7z a socat-1.8.0.0.zip D:\a\socat_windows\socat_windows\socat-1.8.0.0

    - name: Upload Release
      uses: softprops/action-gh-release@v1
      if: ${{  success() }}
      with:
        tag_name: 1.8.0.0
        files: socat-1.8.0.0.zip
